types:
  Recipe:
    parent: false
    resourceEnabled: true
    properties:
###### Start Custom Fields
      name:
        range: Text
        ormColumn: type="string", length=180, nullable=false
        groups:
        - get_recipe
        - set_recipe
      price:
        range: Float
        groups:
        - get_recipe
        - set_recipe
        - get_product
      image:
        range: Text
        ormColumn: nullable=true
        groups:
        - get_recipe
        - set_recipe
        - get_product
      recipeIngredient:
        range: RecipeIngredient
        cardinality: (0..*)
        groups:
        - get_recipe
        - set_recipe
        - get_product
###### End Custom Fields
