security:
    access_decision_manager:
      strategy: unanimous
    encoders:
        NoInc\SimpleStorefront\ApiBundle\Entity\User: bcrypt
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_API:         ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/api/login
            stateless: true
            anonymous: true
            form_login:
                check_path:               /api/login_check
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        api_counts:
            pattern:   ^/api/counts.json
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api_user:
            pattern:   ^/api/user.json
            stateless: true
            anonymous: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        api:
            pattern:   ^/api
            stateless: true
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login
                default_target_path: /app/recipes
                remember_me: true
            logout: true
            anonymous: true
            remember_me:
                secret: %secret%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout$, role: ROLE_USER }
        - { path: ^/app/, role: ROLE_USER }
        - { path: ^/api/user, role: ROLE_USER }
        # - { path: ^/api/user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/counts, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/api/, role: ROLE_USER }
        - { path: ^/api/, role: IS_AUTHENTICATED_FULLY }
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }


