services:
    'NoInc\SimpleStorefront\ApiBundle\Normalizer\RecipeNormalizer':
        decorates: 'api_platform.jsonld.normalizer.item'
        arguments: [ '@NoInc\SimpleStorefront\ApiBundle\Normalizer\RecipeNormalizer.inner' ]
